### ISSUE TITLE
索引长度的问题怎么改

### ISSUE THREAD

**Issue by xiao222-max** [hanzhanggit/StackGAN-inception-model#9]
Traceback (most recent call last):
  File "/home/ml/Pycharmprojects/StackGAN-inception-model-master/inception_score.py", line 233, in <module>
    tf.app.run()
  File "/home/ml/anaconda3/envs/StackGAN/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/ml/Pycharmprojects/StackGAN-inception-model-master/inception_score.py", line 226, in main
    images = load_data(fullpath)
  File "/home/ml/Pycharmprojects/StackGAN-inception-model-master/inception_score.py", line 142, in load_data
    print('images', len(images), images[0].shape)
IndexError: list index out of range
请问这个问题怎么改呀

**Comment by w791862948** [comment]
解决了嘛？我也遇上了同样的问题

**Comment by w791862948** [comment]
> Traceback (most recent call last): File "/home/ml/Pycharmprojects/StackGAN-inception-model-master/inception_score.py", line 233, in tf.app.run() File "/home/ml/anaconda3/envs/StackGAN/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run _sys.exit(main(_sys.argv[:1] + flags_passthrough)) File "/home/ml/Pycharmprojects/StackGAN-inception-model-master/inception_score.py", line 226, in main images = load_data(fullpath) File "/home/ml/Pycharmprojects/StackGAN-inception-model-master/inception_score.py", line 142, in load_data print('images', len(images), images[0].shape) IndexError: list index out of range 请问这个问题怎么改呀

我已经解决了，是图片路径的问题.可以加我微信w791862948讨论一下
